import { chromium } from "playwright-core";
import { readFileSync } from "node:fs";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const BASE = "https://flock-git-feat-inspire-surfaces-aws-projects-a7d3a8cc.vercel.app";
const SHARE = "?_vercel_share=u1afaoCE7WFgOvjf48iI8nE6oAzoSsRt";
const TRIP = "/trips/76a78941-a761-453c-b7ca-60ec8ca187cc";
const PW = readFileSync("/tmp/qa-pw.txt", "utf8").trim();
const browser = await chromium.launch({ executablePath: CHROME });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true, locale: "en" });
const page = await ctx.newPage();
const log = (...a) => console.log("[e2e]", ...a);
const clickText = async (re) => page.evaluate((r) => { const b = [...document.querySelectorAll("button,a")].find(e => new RegExp(r, "i").test(e.textContent?.trim() ?? "") && e.getBoundingClientRect().height > 0); if (b) { b.click(); return b.textContent?.trim().slice(0, 40); } return null; }, re);
await page.goto(BASE + "/" + SHARE, { waitUntil: "domcontentloaded", timeout: 60000 });
await page.waitForTimeout(2000);
await page.goto(BASE + "/auth/login", { waitUntil: "domcontentloaded", timeout: 60000 });
await page.waitForTimeout(2000);
await page.fill('input[type="email"]', "qa.claude.inspire@gmail.com");
await page.fill('input[type="password"]', PW);
await page.click('button[type="submit"]');
await page.waitForTimeout(6000);
await page.goto(BASE + TRIP, { waitUntil: "domcontentloaded", timeout: 60000 });
await page.waitForTimeout(5000);
await clickText("^Decline$");
await page.waitForTimeout(400);
await page.screenshot({ path: "/tmp/paxawa-drag/t1-top.png" });
await page.evaluate(() => window.scrollTo(0, 800));
await page.waitForTimeout(600);
await page.screenshot({ path: "/tmp/paxawa-drag/t2-deck.png" });
const deck = await clickText("Got saved TikToks");
log("deck card:", deck);
await page.waitForTimeout(2500);
await page.screenshot({ path: "/tmp/paxawa-drag/t3-sheet.png" });
const hasTa = await page.$("textarea");
log("sheet textarea:", !!hasTa);
if (hasTa) {
  await page.fill("textarea", "https://vt.tiktok.com/ZSVftC4gG/");
  await clickText("Find the places");
  log("extracting…");
  await page.waitForTimeout(22000);
  await page.screenshot({ path: "/tmp/paxawa-drag/t4-results.png" });
  log("results:", await page.evaluate(() => document.body.innerText.match(/Found \d+ place[s]?|No places[^\n]*/)?.[0] ?? "??"));
  log("save:", await clickText("^Save all|^Save "));
  await page.waitForTimeout(5000);
  await page.screenshot({ path: "/tmp/paxawa-drag/t5-saved.png" });
}
// Discover chip
await page.goto(BASE + TRIP + "/discover", { waitUntil: "domcontentloaded", timeout: 60000 });
await page.waitForTimeout(6000);
await page.screenshot({ path: "/tmp/paxawa-drag/t6-discover.png" });
const chip = await clickText("Import from a link");
log("discover chip:", chip);
await page.waitForTimeout(1800);
await page.screenshot({ path: "/tmp/paxawa-drag/t7-discover-sheet.png" });
// share-target
await page.goto(BASE + "/share-target?text=" + encodeURIComponent("https://vt.tiktok.com/ZSVftymL9/"), { waitUntil: "domcontentloaded", timeout: 60000 });
await page.waitForTimeout(4000);
log("share-target →", page.url());
await page.screenshot({ path: "/tmp/paxawa-drag/t8-share.png" });
const prefilled = await page.evaluate(() => document.querySelector("textarea")?.value ?? null);
log("prefilled:", prefilled);
await browser.close();
