import webpush from "web-push";
import { db } from "@/lib/db";
import { pushSubscriptions } from "@/lib/db/schema";
import { and, eq, inArray } from "drizzle-orm";

/**
 * Web push sender. Same DSN-gating pattern as the email helper: if VAPID
 * keys aren't configured the helper silently no-ops, so server actions can
 * call it without worrying about whether the deploy has push enabled.
 *
 * Required env vars when you want push to actually fire:
 *   VAPID_PUBLIC_KEY       — generated by `npx web-push generate-vapid-keys`
 *   VAPID_PRIVATE_KEY      — same command, keep this server-only
 *   VAPID_SUBJECT          — "mailto:you@example.com"
 *
 * Subscriptions that come back from the push service with 404/410 (the user
 * uninstalled or revoked) are pruned automatically so we don't keep retrying.
 */

let vapidConfigured = false;
function ensureVapid(): boolean {
  if (vapidConfigured) return true;
  const pub = process.env.VAPID_PUBLIC_KEY;
  const priv = process.env.VAPID_PRIVATE_KEY;
  const subject = process.env.VAPID_SUBJECT;
  if (!pub || !priv || !subject) return false;
  webpush.setVapidDetails(subject, pub, priv);
  vapidConfigured = true;
  return true;
}

export interface PushPayload {
  title: string;
  body: string;
  /** Tap-through URL — service worker reads this from data.url. */
  url?: string;
  /** Tag groups notifications so a new vote replaces an older "vote opened"
   *  for the same trip instead of stacking. */
  tag?: string;
  /** Optional icon override (defaults to /icons/icon-192x192.png in SW). */
  icon?: string;
}

interface SendOpts {
  /** Push goes to *every device* this user has subscribed. */
  toUserIds: string[];
  payload: PushPayload;
}

export async function sendPush({ toUserIds, payload }: SendOpts): Promise<void> {
  if (!ensureVapid() || toUserIds.length === 0) return;

  const subs = await db
    .select()
    .from(pushSubscriptions)
    .where(inArray(pushSubscriptions.userId, toUserIds));

  if (subs.length === 0) return;

  const body = JSON.stringify(payload);
  const deadEndpoints: string[] = [];

  await Promise.all(
    subs.map(async (sub) => {
      try {
        await webpush.sendNotification(
          {
            endpoint: sub.endpoint,
            keys: { p256dh: sub.p256dh, auth: sub.auth },
          },
          body,
          { TTL: 60 * 60 }, // 1 hour — drop if the device can't get it
        );
        // Bump last_seen_at so we know it's a live device.
        await db
          .update(pushSubscriptions)
          .set({ lastSeenAt: new Date() })
          .where(eq(pushSubscriptions.id, sub.id))
          .catch(() => {});
      } catch (err: any) {
        const status = err?.statusCode;
        if (status === 404 || status === 410) {
          deadEndpoints.push(sub.endpoint);
        } else {
          console.error("[push] send failed:", status, err?.message);
        }
      }
    }),
  );

  if (deadEndpoints.length > 0) {
    await db
      .delete(pushSubscriptions)
      .where(
        and(
          inArray(pushSubscriptions.endpoint, deadEndpoints),
        ),
      )
      .catch(() => {});
  }
}
